"""initial schema"""

import sqlalchemy as sa

from alembic import op

revision = "9ad12d4b9f43"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "status", sa.Enum("DRAFT", "ACTIVE", "ARCHIVED", name="eventstatus"), nullable=False
        ),
        sa.Column("registration_enabled", sa.Boolean(), nullable=False),
        sa.Column("scanning_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_events_event_time_order")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint("slug", name=op.f("uq_events_slug")),
    )
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("OPERATOR", "ADMIN", name="userrole"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("object_type", sa.String(length=100), nullable=False),
        sa.Column("object_id", sa.String(length=100), nullable=True),
        sa.Column("changes", sa.JSON(), nullable=True),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_logs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_occurred_at"), "audit_logs", ["occurred_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_request_id"), "audit_logs", ["request_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "import_batches",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("uploaded_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "UPLOADED",
                "VALIDATING",
                "VALIDATED",
                "READY_TO_CONFIRM",
                "CONFIRMED",
                "APPLIED",
                "REJECTED",
                "FAILED",
                "CANCELLED",
                name="importstatus",
            ),
            nullable=False,
        ),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("valid_rows", sa.Integer(), nullable=False),
        sa.Column("error_rows", sa.Integer(), nullable=False),
        sa.Column("warning_rows", sa.Integer(), nullable=False),
        sa.Column("created_rows", sa.Integer(), nullable=False),
        sa.Column("updated_rows", sa.Integer(), nullable=False),
        sa.Column("unchanged_rows", sa.Integer(), nullable=False),
        sa.Column("deactivated_rows", sa.Integer(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("preview_version", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_import_batches_event_id_events")
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
            name=op.f("fk_import_batches_uploaded_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
    )
    op.create_index(
        op.f("ix_import_batches_event_id"), "import_batches", ["event_id"], unique=False
    )
    op.create_table(
        "map_assets",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("uploaded_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_map_assets_event_id_events")
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
            name=op.f("fk_map_assets_uploaded_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_map_assets")),
    )
    op.create_index(op.f("ix_map_assets_event_id"), "map_assets", ["event_id"], unique=False)
    op.create_index(
        "uq_active_map_event",
        "map_assets",
        ["event_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "schedule_items",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("map_zone_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "ends_at > starts_at", name=op.f("ck_schedule_items_schedule_time_order")
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_schedule_items_event_id_events")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_items")),
    )
    op.create_index(
        op.f("ix_schedule_items_event_id"), "schedule_items", ["event_id"], unique=False
    )
    op.create_table(
        "user_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_user_sessions_token_hash")),
    )
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.create_table(
        "import_rows",
        sa.Column("import_batch_id", sa.Uuid(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=128), nullable=True),
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.Column("group", sa.String(length=100), nullable=True),
        sa.Column("institute", sa.String(length=300), nullable=True),
        sa.Column("normalized_name", sa.String(length=300), nullable=True),
        sa.Column("normalized_group", sa.String(length=100), nullable=True),
        sa.Column("normalized_institute", sa.String(length=300), nullable=True),
        sa.Column(
            "action",
            sa.Enum("CREATE", "UPDATE", "UNCHANGED", "DEACTIVATE", "ERROR", name="importaction"),
            nullable=False,
        ),
        sa.Column(
            "validation_status",
            sa.Enum("VALID", "WARNING", "ERROR", name="validationstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_import_rows_import_batch_id_import_batches"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_rows")),
        sa.UniqueConstraint(
            "import_batch_id", "row_number", name=op.f("uq_import_rows_import_batch_id")
        ),
    )
    op.create_index(
        op.f("ix_import_rows_import_batch_id"), "import_rows", ["import_batch_id"], unique=False
    )
    op.create_table(
        "source_students",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.String(length=128), nullable=False),
        sa.Column("full_name", sa.String(length=300), nullable=False),
        sa.Column("normalized_full_name", sa.String(length=300), nullable=False),
        sa.Column("study_group", sa.String(length=100), nullable=False),
        sa.Column("normalized_study_group", sa.String(length=100), nullable=False),
        sa.Column("institute", sa.String(length=300), nullable=False),
        sa.Column("normalized_institute", sa.String(length=300), nullable=False),
        sa.Column("source_row_number", sa.Integer(), nullable=True),
        sa.Column("import_batch_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_source_students_event_id_events")
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_source_students_import_batch_id_import_batches"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_students")),
        sa.UniqueConstraint("event_id", "source_id", name=op.f("uq_source_students_event_id")),
    )
    op.create_index(
        op.f("ix_source_students_event_id"), "source_students", ["event_id"], unique=False
    )
    op.create_index(
        "ix_students_group", "source_students", ["event_id", "normalized_study_group"], unique=False
    )
    op.create_index(
        "ix_students_institute",
        "source_students",
        ["event_id", "normalized_institute"],
        unique=False,
    )
    op.create_index(
        "ix_students_registration_lookup",
        "source_students",
        ["event_id", "normalized_full_name", "normalized_study_group"],
        unique=False,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "import_row_errors",
        sa.Column("import_batch_id", sa.Uuid(), nullable=False),
        sa.Column("import_row_id", sa.Uuid(), nullable=True),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=False),
        sa.Column("error_message", sa.String(length=500), nullable=False),
        sa.Column("severity", sa.Enum("ERROR", "WARNING", name="errorseverity"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_import_row_errors_import_batch_id_import_batches"),
        ),
        sa.ForeignKeyConstraint(
            ["import_row_id"],
            ["import_rows.id"],
            name=op.f("fk_import_row_errors_import_row_id_import_rows"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_row_errors")),
    )
    op.create_index(
        op.f("ix_import_row_errors_import_batch_id"),
        "import_row_errors",
        ["import_batch_id"],
        unique=False,
    )
    op.create_table(
        "registrations",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("source_student_id", sa.Uuid(), nullable=False),
        sa.Column("public_id", sa.Uuid(), nullable=False),
        sa.Column(
            "presence_status", sa.Enum("OUTSIDE", "INSIDE", name="presencestatus"), nullable=False
        ),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_registrations_event_id_events")
        ),
        sa.ForeignKeyConstraint(
            ["source_student_id"],
            ["source_students.id"],
            name=op.f("fk_registrations_source_student_id_source_students"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_registrations")),
        sa.UniqueConstraint(
            "event_id", "source_student_id", name=op.f("uq_registrations_event_id")
        ),
        sa.UniqueConstraint("public_id", name=op.f("uq_registrations_public_id")),
    )
    op.create_index(op.f("ix_registrations_event_id"), "registrations", ["event_id"], unique=False)
    op.create_table(
        "qr_tokens",
        sa.Column("registration_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.Enum("ENTRY", "EXIT", name="qrpurpose"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "USED", "REVOKED", "EXPIRED", name="qrstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_by_operator_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["registrations.id"],
            name=op.f("fk_qr_tokens_registration_id_registrations"),
        ),
        sa.ForeignKeyConstraint(
            ["used_by_operator_id"],
            ["users.id"],
            name=op.f("fk_qr_tokens_used_by_operator_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qr_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_qr_tokens_token_hash")),
    )
    op.create_index(
        op.f("ix_qr_tokens_registration_id"), "qr_tokens", ["registration_id"], unique=False
    )
    op.create_index(
        "uq_qr_active_registration",
        "qr_tokens",
        ["registration_id"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "student_sessions",
        sa.Column("registration_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["registrations.id"],
            name=op.f("fk_student_sessions_registration_id_registrations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_student_sessions_token_hash")),
    )
    op.create_index(
        op.f("ix_student_sessions_registration_id"),
        "student_sessions",
        ["registration_id"],
        unique=False,
    )
    op.create_table(
        "attendance_events",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("registration_id", sa.Uuid(), nullable=False),
        sa.Column("operator_id", sa.Uuid(), nullable=False),
        sa.Column("qr_token_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.Enum("ENTRY", "EXIT", name="attendancetype"), nullable=False),
        sa.Column(
            "previous_status", sa.Enum("OUTSIDE", "INSIDE", name="presencestatus"), nullable=False
        ),
        sa.Column(
            "new_status", sa.Enum("OUTSIDE", "INSIDE", name="presencestatus"), nullable=False
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("device_info", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_attendance_events_event_id_events")
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"], ["users.id"], name=op.f("fk_attendance_events_operator_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["qr_token_id"],
            ["qr_tokens.id"],
            name=op.f("fk_attendance_events_qr_token_id_qr_tokens"),
        ),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["registrations.id"],
            name=op.f("fk_attendance_events_registration_id_registrations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance_events")),
        sa.UniqueConstraint("qr_token_id", name=op.f("uq_attendance_events_qr_token_id")),
        sa.UniqueConstraint("request_id", name=op.f("uq_attendance_events_request_id")),
    )
    op.create_index(
        op.f("ix_attendance_events_event_id"), "attendance_events", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_attendance_events_occurred_at"), "attendance_events", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_attendance_events_registration_id"),
        "attendance_events",
        ["registration_id"],
        unique=False,
    )
    op.create_table(
        "scan_attempts",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("operator_id", sa.Uuid(), nullable=False),
        sa.Column("qr_token_id", sa.Uuid(), nullable=True),
        sa.Column("registration_id", sa.Uuid(), nullable=True),
        sa.Column("result", sa.String(length=50), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("response_data", sa.JSON(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("device_info", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_scan_attempts_event_id_events")
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"], ["users.id"], name=op.f("fk_scan_attempts_operator_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["qr_token_id"], ["qr_tokens.id"], name=op.f("fk_scan_attempts_qr_token_id_qr_tokens")
        ),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["registrations.id"],
            name=op.f("fk_scan_attempts_registration_id_registrations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_attempts")),
        sa.UniqueConstraint(
            "operator_id", "idempotency_key", name=op.f("uq_scan_attempts_operator_id")
        ),
    )
    op.create_index(op.f("ix_scan_attempts_event_id"), "scan_attempts", ["event_id"], unique=False)
    op.create_index(
        op.f("ix_scan_attempts_occurred_at"), "scan_attempts", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_scan_attempts_operator_id"), "scan_attempts", ["operator_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scan_attempts_operator_id"), table_name="scan_attempts")
    op.drop_index(op.f("ix_scan_attempts_occurred_at"), table_name="scan_attempts")
    op.drop_index(op.f("ix_scan_attempts_event_id"), table_name="scan_attempts")
    op.drop_table("scan_attempts")
    op.drop_index(op.f("ix_attendance_events_registration_id"), table_name="attendance_events")
    op.drop_index(op.f("ix_attendance_events_occurred_at"), table_name="attendance_events")
    op.drop_index(op.f("ix_attendance_events_event_id"), table_name="attendance_events")
    op.drop_table("attendance_events")
    op.drop_index(op.f("ix_student_sessions_registration_id"), table_name="student_sessions")
    op.drop_table("student_sessions")
    op.drop_index(
        "uq_qr_active_registration",
        table_name="qr_tokens",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_index(op.f("ix_qr_tokens_registration_id"), table_name="qr_tokens")
    op.drop_table("qr_tokens")
    op.drop_index(op.f("ix_registrations_event_id"), table_name="registrations")
    op.drop_table("registrations")
    op.drop_index(op.f("ix_import_row_errors_import_batch_id"), table_name="import_row_errors")
    op.drop_table("import_row_errors")
    op.drop_index(
        "ix_students_registration_lookup",
        table_name="source_students",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_index("ix_students_institute", table_name="source_students")
    op.drop_index("ix_students_group", table_name="source_students")
    op.drop_index(op.f("ix_source_students_event_id"), table_name="source_students")
    op.drop_table("source_students")
    op.drop_index(op.f("ix_import_rows_import_batch_id"), table_name="import_rows")
    op.drop_table("import_rows")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(op.f("ix_schedule_items_event_id"), table_name="schedule_items")
    op.drop_table("schedule_items")
    op.drop_index(
        "uq_active_map_event", table_name="map_assets", postgresql_where=sa.text("is_active")
    )
    op.drop_index(op.f("ix_map_assets_event_id"), table_name="map_assets")
    op.drop_table("map_assets")
    op.drop_index(op.f("ix_import_batches_event_id"), table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_request_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_occurred_at"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("users")
    op.drop_table("events")
    for enum_name in (
        "attendancetype",
        "errorseverity",
        "eventstatus",
        "importaction",
        "importstatus",
        "presencestatus",
        "qrpurpose",
        "qrstatus",
        "userrole",
        "validationstatus",
    ):
        op.execute(sa.text(f'DROP TYPE IF EXISTS "{enum_name}"'))
    # ### end Alembic commands ###
